// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

String? nexoraActiveAccountId;

const _bg = Color(0xFF070A12);
const _panel = Color(0xFF111827);
const _purple = Color(0xFF8B5CF6);
const _cyan = Color(0xFF22D3EE);

class NexoraGameHub extends StatefulWidget {
  const NexoraGameHub({super.key});
  @override State<NexoraGameHub> createState() => _NexoraGameHubState();
}

class _NexoraGameHubState extends State<NexoraGameHub> {
  String filter='ALL', search='';
  static const games=[
    _G('Snake','ARCADE','Eat. Grow. Survive.',Icons.change_history_rounded,Color(0xFF22C55E)),
    _G('2048','PUZZLE','Merge your way to 2048.',Icons.grid_4x4_rounded,Color(0xFFF59E0B)),
    _G('Tetris','ARCADE','Stack fast. Clear lines.',Icons.view_module_rounded,Color(0xFFA855F7)),
    _G('Flappy','ARCADE','One tap. Perfect timing.',Icons.flutter_dash_rounded,Color(0xFF06B6D4)),
    _G('Breakout','ARCADE','Smash the core.',Icons.sports_baseball_rounded,Color(0xFFEF4444)),
    _G('Memory','PUZZLE','Flip. Match. Master.',Icons.style_rounded,Color(0xFFEC4899)),
    _G('Pong','SPORT','First to seven.',Icons.sports_tennis_rounded,Color(0xFF3B82F6)),
    _G('Neon Jump','ARCADE','Climb the skyline.',Icons.bolt_rounded,Color(0xFFD946EF)),
    _G('Minesweeper','PUZZLE','Read the field.',Icons.radar_rounded,Color(0xFFF97316)),
    _G('Simon Says','PUZZLE','Remember the pulse.',Icons.psychology_rounded,Color(0xFF14B8A6)),
    _G('Color Stack','PUZZLE','Sort the spectrum.',Icons.water_drop_rounded,Color(0xFF6366F1)),
  ];
  Widget page(String n){switch(n){case 'Snake':return _Snake();case '2048':return _Twenty();case 'Tetris':return _Tetris();case 'Flappy':return _Flappy();case 'Breakout':return _Breakout();case 'Memory':return _Memory();case 'Pong':return _Pong();case 'Neon Jump':return _Jump();case 'Minesweeper':return _Mines();case 'Simon Says':return _Simon();default:return _ColorStack();}}
  @override Widget build(BuildContext c){final list=games.where((g)=>(filter=='ALL'||g.cat==filter)&&(search.isEmpty||g.name.toLowerCase().contains(search.toLowerCase()))).toList();return Scaffold(backgroundColor:_bg,body:SafeArea(child:ListView(padding:EdgeInsets.fromLTRB(16,14,16,110),children:[
    Container(padding:EdgeInsets.all(20),decoration:BoxDecoration(borderRadius:BorderRadius.circular(30),gradient:LinearGradient(colors:[Color(0xFF27105C),Color(0xFF0C1D38),Color(0xFF090D18)],begin:Alignment.topLeft,end:Alignment.bottomRight),border:Border.all(color:Colors.white10)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
      Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:_purple.withOpacity(.18),borderRadius:BorderRadius.circular(17)),child:Icon(Icons.sports_esports_rounded,color:_purple,size:29)),Spacer(),_Pill('ARCADE COLLECTION')]),
      SizedBox(height:20),Text('NEXORA ARCADE',style:TextStyle(fontSize:12,fontWeight:FontWeight.w900,letterSpacing:2,color:Colors.white54)),SizedBox(height:4),Text('Play. Beat. Repeat.',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900,letterSpacing:-.8)),SizedBox(height:7),Text('11 polished mini games. Instant sessions. Built for one-more-round energy.',style:TextStyle(color:Colors.white60,height:1.35)),SizedBox(height:18),Row(children:[_Stat('11','GAMES'),SizedBox(width:8),_Stat('3','MODES'),SizedBox(width:8),_Stat('∞','REPLAY')])
    ])),
    SizedBox(height:14),TextField(onChanged:(v)=>setState(()=>search=v),style:TextStyle(color:Colors.white),decoration:InputDecoration(prefixIcon:Icon(Icons.search_rounded),hintText:'Search games',filled:true,fillColor:_panel,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none))),
    SizedBox(height:10),SizedBox(height:40,child:ListView(scrollDirection:Axis.horizontal,children:[for(final x in ['ALL','ARCADE','PUZZLE','SPORT'])Padding(padding:EdgeInsets.only(right:8),child:ChoiceChip(label:Text(x),selected:filter==x,onSelected:(_)=>setState(()=>filter=x)))])),
    SizedBox(height:18),Row(children:[Expanded(child:Text('Arcade library',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900))),Text('\${list.length} games',style:TextStyle(color:Colors.white38))]),SizedBox(height:10),
    GridView.builder(shrinkWrap:true,physics:NeverScrollableScrollPhysics(),itemCount:list.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:11,mainAxisSpacing:11,childAspectRatio:.82),itemBuilder:(_,i){final g=list[i];return _GameCard(g,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>page(g.name))));}),
  ])));}

}
class _G{final String name,cat,sub;final IconData icon;final Color color;const _G(this.name,this.cat,this.sub,this.icon,this.color);}
class _Pill extends StatelessWidget{final String t;const _Pill(this.t);Widget build(BuildContext c)=>Container(padding:EdgeInsets.symmetric(horizontal:10,vertical:7),decoration:BoxDecoration(color:Colors.black26,borderRadius:BorderRadius.circular(20),border:Border.all(color:Colors.white10)),child:Text(t,style:TextStyle(fontSize:9,fontWeight:FontWeight.w900,letterSpacing:1,color:Colors.white70)));}
class _Stat extends StatelessWidget{final String a,b;const _Stat(this.a,this.b);Widget build(BuildContext c)=>Expanded(child:Container(padding:EdgeInsets.symmetric(vertical:10),decoration:BoxDecoration(color:Colors.white.withOpacity(.055),borderRadius:BorderRadius.circular(14)),child:Column(children:[Text(a,style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),SizedBox(height:2),Text(b,style:TextStyle(fontSize:8,color:Colors.white38,fontWeight:FontWeight.w800,letterSpacing:1))])));}
class _GameCard extends StatelessWidget{final _G g;final VoidCallback play;const _GameCard(this.g,this.play);Widget build(BuildContext c)=>InkWell(onTap:play,borderRadius:BorderRadius.circular(24),child:Container(decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:LinearGradient(colors:[g.color.withOpacity(.20),Color(0xFF111827)],begin:Alignment.topLeft,end:Alignment.bottomRight),border:Border.all(color:g.color.withOpacity(.22))),child:Stack(children:[Positioned(right:-18,top:-18,child:Container(width:95,height:95,decoration:BoxDecoration(shape:BoxShape.circle,color:g.color.withOpacity(.10)))),Padding(padding:EdgeInsets.all(15),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:52,height:52,decoration:BoxDecoration(color:g.color.withOpacity(.16),borderRadius:BorderRadius.circular(17)),child:Icon(g.icon,color:g.color,size:27)),Spacer(),Text(g.name,style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),SizedBox(height:3),Text(g.sub,maxLines:2,style:TextStyle(fontSize:11,color:Colors.white54,height:1.25)),SizedBox(height:11),Row(children:[Text(g.cat,style:TextStyle(fontSize:9,color:g.color,fontWeight:FontWeight.w900,letterSpacing:1)),Spacer(),Container(width:30,height:30,decoration:BoxDecoration(color:Colors.white.withOpacity(.08),shape:BoxShape.circle),child:Icon(Icons.play_arrow_rounded,size:18))])]))])));}

class _Shell extends StatelessWidget{final String title,subtitle;final Widget child;final Color accent;final VoidCallback? onReset;const _Shell({required this.title,required this.subtitle,required this.child,this.accent=_purple,this.onReset});Widget build(BuildContext c)=>Scaffold(backgroundColor:_bg,body:SafeArea(child:Column(children:[Padding(padding:EdgeInsets.fromLTRB(14,10,14,8),child:Row(children:[IconButton(onPressed:()=>Navigator.pop(c),icon:Icon(Icons.arrow_back_rounded)),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(subtitle,style:TextStyle(fontSize:10,color:Colors.white38))])),if(onReset!=null)IconButton(onPressed:onReset,icon:Icon(Icons.refresh_rounded))])),Expanded(child:child)])));}
class _World extends StatelessWidget{final Widget child;final Color a,b;const _World(this.child,{this.a=Color(0xFF10152A),this.b=Color(0xFF060810)});Widget build(BuildContext c)=>Container(decoration:BoxDecoration(gradient:LinearGradient(colors:[a,b],begin:Alignment.topCenter,end:Alignment.bottomCenter)),child:Stack(children:[Positioned.fill(child:CustomPaint(painter:_Stars())),child]));}
class _Stars extends CustomPainter{final r=Random(8);void paint(Canvas c,Size s){final p=Paint();for(int i=0;i<70;i++){p.color=Colors.white.withOpacity(.04+r.nextDouble()*.08);final x=r.nextDouble()*s.width,y=r.nextDouble()*s.height;c.drawCircle(Offset(x,y),r.nextDouble()*1.5,p);}}bool shouldRepaint(c)=>false;}

class _Snake extends StatefulWidget{const _Snake();State<_Snake> createState()=>_SnakeState();}
class _SnakeState extends State<_Snake>{final r=Random();List<Point<int>> body=[];Point<int> food=Point(7,7),dir=Point(1,0);Timer? timer;int score=0;bool live=false,over=false;@override void initState(){super.initState();reset();}void reset(){timer?.cancel();body=[Point(6,8),Point(5,8),Point(4,8)];dir=Point(1,0);food=Point(r.nextInt(16),r.nextInt(22));score=0;live=false;over=false;}void start(){if(live)return;setState(()=>live=true);timer=Timer.periodic(Duration(milliseconds:max(70,145-score*2)),(_){if(!mounted)return;final h=Point(body.first.x+dir.x,body.first.y+dir.y);if(h.x<0||h.x>=16||h.y<0||h.y>=22||body.contains(h)){timer?.cancel();setState(()=>{live=false;over=true;});return;}setState((){body.insert(0,h);if(h==food){score+=10;do{food=Point(r.nextInt(16),r.nextInt(22));}while(body.contains(food));}else body.removeLast();});});}void turn(Point<int> d){if(dir.x+d.x==0&&dir.y+d.y==0)return;dir=d;start();}Widget build(BuildContext c)=>_Shell(title:'Snake',subtitle:'Cyber Jungle • score $score',accent:Color(0xFF22C55E),onReset:(){setState(reset);},child:GestureDetector(onVerticalDragUpdate:(d)=>d.delta.dy.abs()>d.delta.dx.abs()?turn(Point(0,d.delta.dy>0?1:-1)):null,onHorizontalDragUpdate:(d)=>d.delta.dx.abs()>d.delta.dy.abs()?turn(Point(d.delta.dx>0?1:-1,0)):null,child:_World(Column(children:[Expanded(child:AspectRatio(aspectRatio:16/22,child:Container(margin:EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.black26,borderRadius:BorderRadius.circular(22),border:Border.all(color:Color(0xFF22C55E).withOpacity(.25))),child:CustomPaint(painter:_SnakePainter(body,food))))),if(!live)Padding(padding:EdgeInsets.all(18),child:Column(children:[Text(over?'RUN OVER':'READY?',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),SizedBox(height:7),Text('Swipe to move • tap Start to enter the jungle',style:TextStyle(color:Colors.white54)),SizedBox(height:12),FilledButton(onPressed:start,child:Text(over?'PLAY AGAIN':'START RUN'))]))]))));}
}
class _SnakePainter extends CustomPainter{final List<Point<int>> b;final Point<int> f;_SnakePainter(this.b,this.f);void paint(Canvas c,Size s){final cell=s.width/16;final p=Paint();p.color=Colors.white.withOpacity(.025);for(int x=0;x<16;x++)for(int y=0;y<22;y++)c.drawRect(Rect.fromLTWH(x*cell,y*cell,cell-1,cell-1),p);p.color=Color(0xFFFB7185);c.drawCircle(Offset((f.x+.5)*cell,(f.y+.5)*cell),cell*.27,p);for(int i=b.length-1;i>=0;i--){p.color=i==0?Color(0xFF86EFAC):Color(0xFF22C55E).withOpacity(max(.35,1-i*.025));final q=b[i];c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(q.x*cell+2,q.y*cell+2,cell-4,cell-4),Radius.circular(cell*.25)),p);}}bool shouldRepaint(c)=>true;}

class _Twenty extends StatefulWidget{const _Twenty();State<_Twenty> createState()=>_TwentyState();}
class _TwentyState extends State<_Twenty>{final r=Random();List<int> a=[];int score=0;@override void initState(){super.initState();newGame();}void newGame(){a=List.filled(16,0);score=0;add();add();}void add(){final z=<int>[];for(int i=0;i<16;i++)if(a[i]==0)z.add(i);if(z.isNotEmpty)a[z[r.nextInt(z.length)]]=r.nextDouble()<.9?2:4;}bool move(int dx,int dy){List<int> n=List.filled(16,0);bool changed=false;for(int line=0;line<4;line++){final vals=<int>[];for(int k=0;k<4;k++){final x=dx!=0?(dx>0?3-k:k):line;final y=dy!=0?(dy>0?3-k:k):line;final v=a[y*4+x];if(v>0)vals.add(v);}final out=<int>[];for(int i=0;i<vals.length;i++){if(i+1<vals.length&&vals[i]==vals[i+1]){out.add(vals[i]*2);score+=vals[i]*2;i++;}else out.add(vals[i]);}while(out.length<4)out.add(0);for(int k=0;k<4;k++){final x=dx!=0?(dx>0?3-k:k):line;final y=dy!=0?(dy>0?3-k:k):line;n[y*4+x]=out[k];}}changed=n.toString()!=a.toString();if(changed){a=n;add();}return changed;}Widget build(BuildContext c)=>_Shell(title:'2048',subtitle:'Quantum Merge • $score pts',accent:Color(0xFFF59E0B),onReset:()=>setState(newGame),child:GestureDetector(onVerticalDragEnd:(d)=>move(0,d.primaryVelocity!<0?1:-1),onHorizontalDragEnd:(d)=>move(d.primaryVelocity!<0?1:-1,0),child:_World(Column(children:[Padding(padding:EdgeInsets.all(16),child:Row(children:[_Mini('SCORE','$score'),Spacer(),_Mini('GOAL','2048')])),Expanded(child:Center(child:Container(width:min(MediaQuery.sizeOf(c).width-30,380),padding:EdgeInsets.all(9),decoration:BoxDecoration(color:Colors.white.withOpacity(.04),borderRadius:BorderRadius.circular(24),border:Border.all(color:Colors.white10)),child:GridView.builder(physics:NeverScrollableScrollPhysics(),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:4,crossAxisSpacing:8,mainAxisSpacing:8),itemCount:16,itemBuilder:(_,i){final v=a[i];return AnimatedContainer(duration:Duration(milliseconds:130),decoration:BoxDecoration(color:v==0?Colors.white.withOpacity(.04):Color.lerp(Color(0xFF1F2937),Color(0xFFF59E0B),min(1,log(max(1,v))/log(2048)))!,borderRadius:BorderRadius.circular(15)),child:Center(child:Text(v==0?'':v.toString(),style:TextStyle(fontSize:v>999?20:27,fontWeight:FontWeight.w900))))}))),),Padding(padding:EdgeInsets.all(16),child:Text('Swipe to merge tiles • build the highest chain',style:TextStyle(color:Colors.white38)))]))));}
}
class _Mini extends StatelessWidget{final String a,b;const _Mini(this.a,this.b);Widget build(BuildContext c)=>Container(padding:EdgeInsets.symmetric(horizontal:13,vertical:9),decoration:BoxDecoration(color:Colors.white.withOpacity(.05),borderRadius:BorderRadius.circular(14)),child:Column(children:[Text(a,style:TextStyle(fontSize:8,color:Colors.white38)),Text(b,style:TextStyle(fontWeight:FontWeight.w900))]));}

class _Tetris extends StatefulWidget{const _Tetris();State<_Tetris> createState()=>_TetrisState();}
class _TetrisState extends State<_Tetris>{final r=Random();List<List<int>> g=List.generate(20,(_)=>List.filled(10,0));int px=3,py=0,rot=0,type=0,score=0,lines=0;Timer? t;final shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]]];@override void initState(){super.initState();spawn();t=Timer.periodic(Duration(milliseconds:620),(_){if(mounted)setState(()=>drop());});}void spawn(){type=r.nextInt(shapes.length);px=3;py=0;rot=0;if(hit(px,py,shape())){t?.cancel();}}List<List<int>> shape(){var s=shapes[type].map((x)=>x.toList()).toList();for(int z=0;z<rot;z++){s=List.generate(s[0].length,(x)=>List.generate(s.length,(y)=>s[s.length-1-y][x]));}return s;}bool hit(int x,int y,List<List<int>> s){for(int yy=0;yy<s.length;yy++)for(int xx=0;xx<s[yy].length;xx++)if(s[yy][xx]>0&&(y+yy>=20||x+xx<0||x+xx>=10||(y+yy>=0&&g[y+yy][x+xx]>0)))return true;return false;}void lock(){final s=shape();for(int y=0;y<s.length;y++)for(int x=0;x<s[y].length;x++)if(s[y][x]>0&&py+y>=0)g[py+y][px+x]=type+1;int cleared=0;g.removeWhere((row){if(row.every((v)=>v>0)){cleared++;return true;}return false;});while(g.length<20)g.insert(0,List.filled(10,0));lines+=cleared;score+=cleared*100;spawn();}void drop(){if(!hit(px,py+1,shape()))py++;else lock();}void move(int d){if(!hit(px+d,py,shape()))px+=d;}void rotate(){rot=(rot+1)%4;if(hit(px,py,shape()))rot=(rot+3)%4;}@override void dispose(){t?.cancel();super.dispose();}Widget build(BuildContext c){final s=shape();return _Shell(title:'Tetris',subtitle:'Reactor Stack • $score pts • $lines lines',accent:_purple,onReset:(){setState((){g=List.generate(20,(_)=>List.filled(10,0));score=0;lines=0;spawn();});},child:_World(Column(children:[Expanded(child:Center(child:AspectRatio(aspectRatio:.5,child:Container(margin:EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.black45,borderRadius:BorderRadius.circular(18),border:Border.all(color:_purple.withOpacity(.3))),child:CustomPaint(painter:_TetPainter(g,px,py,s,type))))),),Padding(padding:EdgeInsets.fromLTRB(20,5,20,18),child:Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[_Ctl(Icons.arrow_left_rounded,()=>setState(()=>move(-1))),_Ctl(Icons.rotate_right_rounded,()=>setState(rotate)),_Ctl(Icons.arrow_downward_rounded,()=>setState(drop)),_Ctl(Icons.arrow_right_rounded,()=>setState(()=>move(1)))])])));}}
class _Ctl extends StatelessWidget{final IconData i;final VoidCallback f;const _Ctl(this.i,this.f);Widget build(BuildContext c)=>InkWell(onTap:f,borderRadius:BorderRadius.circular(16),child:Container(width:58,height:52,decoration:BoxDecoration(color:Colors.white.withOpacity(.06),borderRadius:BorderRadius.circular(16)),child:Icon(i)));}
class _TetPainter extends CustomPainter{final List<List<int>>g;final int px,py,type;final List<List<int>>s;_TetPainter(this.g,this.px,this.py,this.s,this.type);void paint(Canvas c,Size z){final w=z.width/10,h=z.height/20,p=Paint();for(int y=0;y<20;y++)for(int x=0;x<10;x++){p.color=g[y][x]==0?Colors.white.withOpacity(.025):_tc(g[y][x]-1);c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(x*w+2,y*h+2,w-4,h-4),Radius.circular(4)),p);}p.color=_tc(type);for(int y=0;y<s.length;y++)for(int x=0;x<s[y].length;x++)if(s[y][x]>0)c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH((px+x)*w+2,(py+y)*h+2,w-4,h-4),Radius.circular(4)),p);}Color _tc(int i)=>[Color(0xFF22D3EE),Color(0xFFFBBF24),Color(0xFFD946EF),Color(0xFF3B82F6),Color(0xFFF97316),Color(0xFF22C55E),Color(0xFFEF4444)][i.clamp(0,6)];bool shouldRepaint(c)=>true;}

class _Flappy extends StatefulWidget{const _Flappy();State<_Flappy> createState()=>_FlappyState();}
class _FlappyState extends State<_Flappy>{double y=0,v=0;int score=0;bool started=false,over=false;Timer? t;List<double> pipes=[1.1,1.9];void flap(){if(over){reset();}started=true;v=-.72;}void reset(){y=0;v=0;score=0;started=false;over=false;pipes=[1.1,1.9];} @override void initState(){super.initState();t=Timer.periodic(Duration(milliseconds:30),(_){if(!mounted||!started||over)return;setState((){v+=.045;y+=v;pipes=[for(final x in pipes)x-.012];for(int i=0;i<pipes.length;i++)if(pipes[i]<-.18){pipes[i]=1.65;score++;}final hitY=(y+1)/2;for(final p in pipes)if((p-.13).abs()<.12&&(hitY<.35||hitY>.65))over=true;if(y<-1||y>1)over=true;});});} @override void dispose(){t?.cancel();super.dispose();}Widget build(BuildContext c)=>_Shell(title:'Flappy',subtitle:'Sky Circuit • $score gates',accent:_cyan,onReset:()=>setState(reset),child:GestureDetector(onTap:flap,child:_World(_FlappyField(y,pipes,score,over),a:Color(0xFF083344),b:Color(0xFF07111F))));}
class _FlappyField extends StatelessWidget{final double y;final List<double>pipes;final int score;final bool over;const _FlappyField(this.y,this.pipes,this.score,this.over);Widget build(BuildContext c)=>Stack(children:[CustomPaint(size:Size.infinite,painter:_FlapPainter(y,pipes)),if(!over&&score==0)Center(child:Container(padding:EdgeInsets.symmetric(horizontal:22,vertical:16),decoration:BoxDecoration(color:Colors.black45,borderRadius:BorderRadius.circular(20),border:Border.all(color:_cyan.withOpacity(.3))),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.touch_app_rounded,color:_cyan,size:30),SizedBox(height:8),Text('TAP TO FLY',style:TextStyle(fontWeight:FontWeight.w900)),SizedBox(height:3),Text('Thread the neon gates',style:TextStyle(color:Colors.white54,fontSize:11))]))),if(over)Center(child:Container(padding:EdgeInsets.all(24),decoration:BoxDecoration(color:Color(0xEE0B1220),borderRadius:BorderRadius.circular(24)),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('RUN OVER',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),SizedBox(height:5),Text('$score gates cleared',style:TextStyle(color:Colors.white54)),SizedBox(height:12),FilledButton(onPressed:()=>c.findAncestorStateOfType<_FlappyState>()?.flap(),child:Text('RETRY'))]))) ]);}
class _FlapPainter extends CustomPainter{final double y;final List<double>pipes;_FlapPainter(this.y,this.pipes);void paint(Canvas c,Size s){final p=Paint();p.color=Colors.white.withOpacity(.06);for(int i=0;i<25;i++){c.drawCircle(Offset((i*97.0)%s.width,(i*47.0)%s.height),1.5,p);}for(final x in pipes){final px=x*s.width;p.color=_cyan.withOpacity(.75);c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(px,0,42,s.height*.35),Radius.circular(14)),p);c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(px,s.height*.65,42,s.height*.35),Radius.circular(14)),p);}p.color=Color(0xFFFBBF24);final by=(y+1)/2*s.height;c.drawCircle(Offset(s.width*.2,by),15,p);p.color=Colors.white;c.drawCircle(Offset(s.width*.2+5,by-3),3,p);}bool shouldRepaint(c)=>true;}

class _Breakout extends StatefulWidget{const _Breakout();State<_Breakout> createState()=>_BreakoutState();}
class _BreakoutState extends State<_Breakout>{double bx=.5,by=.78,dx=.006,dy=-.007,paddle=.5;int score=0,lives=3;Timer? t;List<bool> bricks=List.filled(24,true);@override void initState(){super.initState();t=Timer.periodic(Duration(milliseconds:16),(_){if(mounted)setState(step);});}void step(){bx+=dx;by+=dy;if(bx<.03||bx>.97)dx=-dx;if(by<.03)dy=dy.abs();if(by>.9){if((bx-paddle).abs()<.15){dy=-dy.abs();by=.88;}else{lives--;if(lives<=0){lives=3;score=0;bricks=List.filled(24,true);}bx=.5;by=.78;dx=.006;dy=-.007;}}for(int i=0;i<24;i++){if(!bricks[i])continue;final col=i%6,row=i~/6;final l=.08+col*.14,r=l+.11,top=.12+row*.065;if(bx>l&&bx<r&&by>top&&by<top+.045){bricks[i]=false;score+=10;dy=-dy;break;}}if(bricks.every((x)=>!x)){bricks=List.filled(24,true);score+=100;}}@override void dispose(){t?.cancel();super.dispose();}Widget build(BuildContext c)=>_Shell(title:'Breakout',subtitle:'Solar Core • $score pts • $lives lives',accent:Color(0xFFEF4444),onReset:()=>setState((){score=0;lives=3;bricks=List.filled(24,true);}),child:GestureDetector(onHorizontalDragUpdate:(d){setState(()=>paddle=(paddle+d.delta.dx/MediaQuery.sizeOf(c).width).clamp(.12,.88));},child:_World(CustomPaint(painter:_BreakPainter(bx,by,paddle,bricks)),a:Color(0xFF3B0A0A),b:Color(0xFF090A12))));}}
class _BreakPainter extends CustomPainter{final double bx,by,paddle;final List<bool>b;_BreakPainter(this.bx,this.by,this.paddle,this.b);void paint(Canvas c,Size s){final p=Paint();for(int i=0;i<24;i++){if(!b[i])continue;final col=i%6,row=i~/6;p.color=[Color(0xFFF97316),Color(0xFFF59E0B),Color(0xFFEF4444),Color(0xFFEC4899),Color(0xFFA855F7),Color(0xFF22D3EE)][col];final rect=Rect.fromLTWH(s.width*(.08+col*.14),s.height*(.12+row*.065),s.width*.11,s.height*.045);c.drawRRect(RRect.fromRectAndRadius(rect,Radius.circular(7)),p);}p.color=Color(0xFFF8FAFC);c.drawCircle(Offset(bx*s.width,by*s.height),7,p);p.color=Color(0xFFEF4444);c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH((paddle-.12)*s.width,s.height*.9,s.width*.24,12),Radius.circular(8)),p);}bool shouldRepaint(c)=>true;}

class _Memory extends StatefulWidget{const _Memory();State<_Memory> createState()=>_MemoryState();}
class _MemoryState extends State<_Memory>{final r=Random();late List<int> cards;List<int> open=[];Set<int>done={};int moves=0;Timer? timer;int sec=0;@override void initState(){super.initState();reset();}void reset(){cards=[0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7]..shuffle(r);open=[];done={};moves=0;sec=0;timer?.cancel();timer=Timer.periodic(Duration(seconds:1),(_){if(mounted)setState(()=>sec++);});}void tap(int i){if(open.length==2||open.contains(i)||done.contains(i))return;setState(()=>open.add(i));if(open.length==2){moves++;Future.delayed(Duration(milliseconds:520),(){if(!mounted)return;setState((){if(cards[open[0]]==cards[open[1]])done.addAll(open);open=[];});});}}@override void dispose(){timer?.cancel();super.dispose();}Widget build(BuildContext c)=>_Shell(title:'Memory',subtitle:'Hologram Match • $moves moves • ${sec}s',accent:Color(0xFFEC4899),onReset:()=>setState(reset),child:_World(Padding(padding:EdgeInsets.all(16),child:GridView.builder(gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:4,crossAxisSpacing:9,mainAxisSpacing:9),itemCount:16,itemBuilder:(_,i){final shown=open.contains(i)||done.contains(i);return GestureDetector(onTap:()=>tap(i),child:AnimatedContainer(duration:Duration(milliseconds:180),decoration:BoxDecoration(gradient:shown?LinearGradient(colors:[Color(0xFFEC4899),Color(0xFF7C3AED)]):LinearGradient(colors:[Color(0xFF172033),Color(0xFF0D1424)]),borderRadius:BorderRadius.circular(17),border:Border.all(color:shown?Colors.white24:Colors.white10)),child:Center(child:shown?Icon([Icons.bolt,Icons.rocket_launch,Icons.diamond,Icons.star,Icons.favorite,Icons.flash_on,Icons.bubble_chart,Icons.auto_awesome][cards[i]],size:30):Icon(Icons.question_mark_rounded,color:Colors.white24))))})));}

class _Pong extends StatefulWidget{const _Pong();State<_Pong> createState()=>_PongState();}
class _PongState extends State<_Pong>{double py=.5,cy=.5,bx=.5,by=.5,dx=.008,dy=.006;int me=0,cpu=0;Timer? t;@override void initState(){super.initState();t=Timer.periodic(Duration(milliseconds:16),(_){if(mounted)setState(step);});}void resetBall(int dir){bx=.5;by=.5;dx=.008*dir;dy=(Random().nextDouble()-.5)*.012;}void step(){bx+=dx;by+=dy;if(by<.04||by>.96)dy=-dy;if((bx<.08&& (by-py).abs()<.13)||(bx>.92&&(by-cy).abs()<.13)){dx=-dx*1.02;}cy+=(by-cy)*.035;if(bx<0){cpu++;resetBall(1);}if(bx>1){me++;resetBall(-1);}}@override void dispose(){t?.cancel();super.dispose();}Widget build(BuildContext c)=>_Shell(title:'Pong',subtitle:'Neon Stadium • $me : $cpu • first to 7',accent:Color(0xFF3B82F6),onReset:()=>setState((){me=0;cpu=0;resetBall(1);}),child:GestureDetector(onVerticalDragUpdate:(d){setState(()=>py=(py+d.delta.dy/MediaQuery.sizeOf(c).height).clamp(.12,.88));},child:_World(CustomPaint(painter:_PongPainter(bx,by,py,cy,me,cpu)),a:Color(0xFF071A3A),b:Color(0xFF050812))));}}
class _PongPainter extends CustomPainter{final double bx,by,py,cy;final int me,cpu;_PongPainter(this.bx,this.by,this.py,this.cy,this.me,this.cpu);void paint(Canvas c,Size s){final p=Paint();p.color=Colors.white10;for(int i=0;i<12;i++)c.drawRect(Rect.fromLTWH(s.width/2-1,i*s.height/12+5,2,s.height/24),p);p.color=Color(0xFF60A5FA);c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(18,(py-.1)*s.height,10,s.height*.2),Radius.circular(7)),p);p.color=Color(0xFFF472B6);c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(s.width-28,(cy-.1)*s.height,10,s.height*.2),Radius.circular(7)),p);p.color=Colors.white;c.drawCircle(Offset(bx*s.width,by*s.height),8,p);TextPainter(TextSpan(text:'$me',style:TextStyle(fontSize:42,fontWeight:FontWeight.w900,color:Colors.white12)),textDirection:TextDirection.ltr)..layout()..paint(c,Offset(s.width*.33,18));TextPainter(TextSpan(text:'$cpu',style:TextStyle(fontSize:42,fontWeight:FontWeight.w900,color:Colors.white12)),textDirection:TextDirection.ltr)..layout()..paint(c,Offset(s.width*.58,18));}bool shouldRepaint(c)=>true;}

class _Jump extends StatefulWidget{const _Jump();State<_Jump> createState()=>_JumpState();}
class _JumpState extends State<_Jump>{double x=.5,y=.75,vy=0;int score=0;Timer? t;List<double> plats=[.78,.58,.38,.18];@override void initState(){super.initState();t=Timer.periodic(Duration(milliseconds:16),(_){if(mounted)setState(step);});}void step(){vy+=.012;y+=vy;if(y>.84){y=.84;vy=-.18;score++;}for(int i=0;i<plats.length;i++){plats[i]+=.004;if(plats[i]>.95)plats[i]=.08-randomOffset(i);if((y-plats[i]).abs()<.025&&vy>0&&x>platformX(i)-.1&&x<platformX(i)+.1)vy=-.18;}if(y<.02)y=.02;}double platformX(int i)=>[.25,.72,.42,.78][i];double randomOffset(int i)=>((i*17)%9)/100;@override void dispose(){t?.cancel();super.dispose();}Widget build(BuildContext c)=>_Shell(title:'Neon Jump',subtitle:'Skyline Run • $score hops',accent:Color(0xFFD946EF),child:GestureDetector(onTap:(){setState(()=>vy=-.21);},onHorizontalDragUpdate:(d){setState(()=>x=(x+d.delta.dx/MediaQuery.sizeOf(c).width).clamp(.08,.92));},child:_World(CustomPaint(painter:_JumpPainter(x,y,plats,platformX)),a:Color(0xFF220A3D),b:Color(0xFF070A16))));}}
class _JumpPainter extends CustomPainter{final double x,y;final List<double>p;final double Function(int)i;_JumpPainter(this.x,this.y,this.p,this.i);void paint(Canvas c,Size s){final paint=Paint();for(int k=0;k<p.length;k++){paint.color=[Color(0xFFD946EF),Color(0xFF22D3EE),Color(0xFFA78BFA),Color(0xFFF472B6)][k];c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH((i(k)-.12)*s.width,p[k]*s.height,s.width*.24,9),Radius.circular(8)),paint);}paint.color=Color(0xFFFBBF24);c.drawCircle(Offset(x*s.width,y*s.height),15,paint);paint.color=Colors.white;c.drawCircle(Offset(x*s.width+5,y*s.height-4),3,paint);}bool shouldRepaint(c)=>true;}

class _Mines extends StatefulWidget{const _Mines();State<_Mines> createState()=>_MinesState();}
class _MinesState extends State<_Mines>{final r=Random();late List<bool> mine;late List<int> nums;Set<int> open={},flags={};bool lost=false,won=false;@override void initState(){super.initState();reset();}void reset(){mine=List.filled(81,false);nums=List.filled(81,0);open={};flags={};lost=false;won=false;int n=0;while(n<11){final i=r.nextInt(81);if(!mine[i]){mine[i]=true;n++;}}for(int i=0;i<81;i++){if(mine[i])continue;final x=i%9,y=i~/9;int z=0;for(int yy=-1;yy<=1;yy++)for(int xx=-1;xx<=1;xx++){final nx=x+xx,ny=y+yy;if(nx>=0&&nx<9&&ny>=0&&ny<9&&mine[ny*9+nx])z++;}nums[i]=z;}}void reveal(int i){if(lost||won||flags.contains(i)||open.contains(i))return;if(mine[i]){setState((){lost=true;open=Set.from(List.generate(81,(j)=>j));});return;}setState(()=>open.add(i));if(open.length>=70)won=true;}Widget build(BuildContext c)=>_Shell(title:'Minesweeper',subtitle:'Hazard Command • 11 mines • ${flags.length} flags',accent:Color(0xFFF97316),onReset:()=>setState(reset),child:_World(Padding(padding:EdgeInsets.all(14),child:GridView.builder(gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:9,crossAxisSpacing:3,mainAxisSpacing:3),itemCount:81,itemBuilder:(_,i){final shown=open.contains(i);return GestureDetector(onTap:()=>reveal(i),onLongPress:(){if(open.contains(i))return;setState(()=>flags.contains(i)?flags.remove(i):flags.add(i));},child:Container(decoration:BoxDecoration(color:shown?Colors.white.withOpacity(.06):Color(0xFF182233),borderRadius:BorderRadius.circular(6),border:Border.all(color:Colors.white10)),child:Center(child:flags.contains(i)?Icon(Icons.flag_rounded,color:Color(0xFFF97316),size:17):shown?(mine[i]?Icon(Icons.warning_rounded,color:Colors.redAccent,size:18):Text('${nums[i]}',style:TextStyle(fontWeight:FontWeight.w900,color: nums[i]==0?Colors.transparent:(nums[i]==1?Color(0xFF22D3EE):nums[i]==2?Color(0xFF22C55E):nums[i]==3?Color(0xFFFBBF24):Color(0xFFF97316))))):null)));})));}

class _Simon extends StatefulWidget{const _Simon();State<_Simon> createState()=>_SimonState();}
class _SimonState extends State<_Simon>{final r=Random();List<int> seq=[];int at=0,flash=-1;bool accepting=false;int score=0;@override void initState(){super.initState();start();}void start(){seq=[];at=0;score=0;next();}void next(){seq.add(r.nextInt(4));playSequence();}Future<void> playSequence()async{setState(()=>accepting=false);for(final x in seq){if(!mounted)return;setState(()=>flash=x);await Future.delayed(Duration(milliseconds:350));if(!mounted)return;setState(()=>flash=-1);await Future.delayed(Duration(milliseconds:120));}if(mounted)setState(()=>accepting=true);}void tap(int x){if(!accepting)return;if(seq[at]!=x){setState(()=>accepting=false);Future.delayed(Duration(milliseconds:500),(){if(mounted)start();});return;}at++;if(at==seq.length){score++;at=0;Future.delayed(Duration(milliseconds:300),(){if(mounted)next();});}}@override Widget build(BuildContext c)=>_Shell(title:'Simon Says',subtitle:'Pulse Memory • streak $score',accent:Color(0xFF14B8A6),onReset:()=>setState(start),child:_World(Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(flash>=0?'WATCH':'YOUR TURN',style:TextStyle(fontSize:14,fontWeight:FontWeight.w900,color:Colors.white54,letterSpacing:2)),SizedBox(height:18),Padding(padding:EdgeInsets.all(22),child:GridView.count(shrinkWrap:true,crossAxisCount:2,crossAxisSpacing:14,mainAxisSpacing:14,children:[for(int i=0;i<4;i++)GestureDetector(onTap:()=>tap(i),child:AnimatedContainer(duration:Duration(milliseconds:100),decoration:BoxDecoration(color:[Color(0xFF22C55E),Color(0xFFF97316),Color(0xFF3B82F6),Color(0xFFD946EF)][i].withOpacity(flash==i?.95:.45),borderRadius:BorderRadius.circular(30),boxShadow:[if(flash==i)BoxShadow(color:[Color(0xFF22C55E),Color(0xFFF97316),Color(0xFF3B82F6),Color(0xFFD946EF)][i].withOpacity(.35),blurRadius:30)])),child:Icon([Icons.circle,Icons.square_rounded,Icons.change_history_rounded,Icons.diamond_rounded][i],size:36,color:Colors.white70))))]))]));}

class _ColorStack extends StatefulWidget{const _ColorStack();State<_ColorStack> createState()=>_ColorStackState();}
class _ColorStackState extends State<_ColorStack>{final r=Random();late List<List<int>> tubes;int? selected;int moves=0;@override void initState(){super.initState();reset();}void reset(){tubes=[[0,1,2,3],[0,1,2,3],[4,5,6,7],[4,5,6,7],[],[]];tubes=tubes.map((x)=>x.toList()).toList();for(final x in tubes)x.shuffle(r);selected=null;moves=0;}bool solved(List<int>x)=>x.isEmpty||(x.length==4&&x.every((v)=>v==x.first));void tap(int i){if(selected==null){if(tubes[i].isNotEmpty&&!solved(tubes[i]))setState(()=>selected=i);return;}if(i==selected){setState(()=>selected=null);return;}final from=tubes[selected!],to=tubes[i];if(to.length>=4){setState(()=>selected=null);return;}final color=from.last;int count=0;for(int k=from.length-1;k>=0&&from[k]==color;k--)count++;if(to.isNotEmpty&&to.last!=color){setState(()=>selected=null);return;}final take=min(count,4-to.length);setState((){for(int k=0;k<take;k++)to.add(from.removeLast());moves++;selected=null;});}Widget build(BuildContext c)=>_Shell(title:'Color Stack',subtitle:'Chromatic Lab • $moves moves',accent:Color(0xFF6366F1),onReset:()=>setState(reset),child:_World(Center(child:Wrap(alignment:WrapAlignment.center,spacing:18,runSpacing:22,children:[for(int i=0;i<tubes.length;i++)GestureDetector(onTap:()=>tap(i),child:AnimatedContainer(duration:Duration(milliseconds:180),width:55,height:170,padding:EdgeInsets.all(6),decoration:BoxDecoration(color:selected==i?Color(0xFF6366F1).withOpacity(.16):Colors.white.withOpacity(.035),borderRadius:BorderRadius.circular(22),border:Border.all(color:selected==i?Color(0xFF818CF8):Colors.white10)),child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[for(final v in tubes[i])Container(height:36,margin:EdgeInsets.only(bottom:3),decoration:BoxDecoration(color:[Color(0xFF22D3EE),Color(0xFFF59E0B),Color(0xFFEC4899),Color(0xFF22C55E),Color(0xFFA78BFA),Color(0xFFF97316),Color(0xFF60A5FA),Color(0xFFF43F5E)][v],borderRadius:BorderRadius.circular(11))),]))]))));}
