
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';

const _purple=Color(0xFF8B5CF6);

class NexoraGameHub extends StatefulWidget{const NexoraGameHub({super.key});@override State<NexoraGameHub> createState()=>_HubState();}
class _HubState extends State<NexoraGameHub>{
  String filter='ALL',q='';
  final data=[
    ['Snake','ARCADE',Icons.straighten_rounded,Color(0xFF22C55E),'Grow and survive'],['2048','PUZZLE',Icons.grid_4x4_rounded,Color(0xFFF59E0B),'Merge numbers'],['Tetris','ARCADE',Icons.view_module_rounded,Color(0xFF8B5CF6),'Clear lines'],['Flappy','ARCADE',Icons.flutter_dash_rounded,Color(0xFF06B6D4),'Fly through pipes'],['Breakout','ARCADE',Icons.sports_baseball_rounded,Color(0xFFEF4444),'Smash the bricks'],['Memory','PUZZLE',Icons.style_rounded,Color(0xFFEC4899),'Find every pair'],['Pong','SPORT',Icons.sports_tennis_rounded,Color(0xFF3B82F6),'Beat the AI'],['Whack-a-Mole','ARCADE',Icons.ads_click_rounded,Color(0xFFA855F7),'Tap the target'],['Minesweeper','PUZZLE',Icons.warning_amber_rounded,Color(0xFFF97316),'Find safe cells'],['Simon Says','PUZZLE',Icons.psychology_rounded,Color(0xFF14B8A6),'Remember colors'],
  ];
  Widget game(String n){switch(n){case'Snake':return const _Snake();case'2048':return const _Twenty48();case'Tetris':return const _Tetris();case'Flappy':return const _Flappy();case'Breakout':return const _Breakout();case'Memory':return const _Memory();case'Pong':return const _Pong();case'Whack-a-Mole':return const _Whack();case'Minesweeper':return const _Mines();default:return const _Simon();}}
  @override Widget build(BuildContext c){
    final list=data.where((g)=>(filter=='ALL'||g[1]==filter)&&(g[0] as String).toLowerCase().contains(q.toLowerCase())).toList();
    return ListView(padding:const EdgeInsets.fromLTRB(14,14,14,110),children:[
      Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(borderRadius:BorderRadius.circular(28),gradient:const LinearGradient(colors:[Color(0xFF4C1D95),Color(0xFF172554),Color(0xFF07111F)])),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
        Row(children:[Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:Colors.white12,borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.sports_esports_rounded,size:28)),const Spacer(),const _Tag('10 GAMES')]),
        const SizedBox(height:16),const Text('NEXORA GAME HUB',style:TextStyle(fontSize:11,fontWeight:FontWeight.w900,letterSpacing:1.8,color:Colors.white70)),const SizedBox(height:5),const Text('Play. Beat. Repeat.',style:TextStyle(fontSize:29,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('10 mini game original Nexora. Offline dan langsung main.',style:TextStyle(color:Colors.white70)),
        const SizedBox(height:17),Row(children:[_MiniStat('ARCADE','5'),const SizedBox(width:8),_MiniStat('PUZZLE','4'),const SizedBox(width:8),_MiniStat('SPORT','1')]),
      ])),
      const SizedBox(height:14),TextField(onChanged:(v)=>setState(()=>q=v),decoration:InputDecoration(prefixIcon:const Icon(Icons.search_rounded),hintText:'Cari game...',filled:true,fillColor:const Color(0xFF111522),border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none))),
      const SizedBox(height:10),SizedBox(height:42,child:ListView(scrollDirection:Axis.horizontal,children:[for(final f in const['ALL','ARCADE','PUZZLE','SPORT'])Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(label:Text(f),selected:filter==f,onSelected:(_)=>setState(()=>filter=f)))])),
      const SizedBox(height:14),Row(children:[const Expanded(child:Text('All Games',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900))),Text(list.length.toString()+' tersedia',style:const TextStyle(color:Colors.white54))]),const SizedBox(height:10),
      GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:list.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:.78),itemBuilder:(_,i){
        final g=list[i],name=g[0] as String,color=g[3] as Color;
        return Card(clipBehavior:Clip.antiAlias,child:InkWell(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>game(name))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
          Expanded(child:Container(decoration:BoxDecoration(gradient:LinearGradient(colors:[color.withOpacity(.75),const Color(0xFF111522)])),child:Stack(children:[Positioned(right:-18,top:-18,child:Icon(g[2] as IconData,size:100,color:Colors.white10)),Center(child:Icon(g[2] as IconData,size:52)),Positioned(left:10,top:10,child:_Tag(g[1] as String))]))),
          Padding(padding:const EdgeInsets.fromLTRB(12,10,12,12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16)),const SizedBox(height:3),Text(g[4] as String,style:const TextStyle(fontSize:11,color:Colors.white60)),const SizedBox(height:9),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>game(name))),icon:const Icon(Icons.play_arrow_rounded,size:18),label:const Text('PLAY'))])),
        ])));
      }),
    ]);
  }
}
class _Tag extends StatelessWidget{final String t;const _Tag(this.t);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:7),decoration:BoxDecoration(color:Colors.black26,borderRadius:BorderRadius.circular(30)),child:Text(t,style:const TextStyle(fontSize:9,fontWeight:FontWeight.w900,letterSpacing:1)));}
class _MiniStat extends StatelessWidget{final String a,b;const _MiniStat(this.a,this.b);@override Widget build(BuildContext c)=>Expanded(child:Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:Colors.white10,borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:8,color:Colors.white60)),Text(b,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900))])));}
class _Shell extends StatelessWidget{final String title;final Widget child;final VoidCallback restart;const _Shell(this.title,this.child,this.restart);@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title,style:const TextStyle(fontWeight:FontWeight.w900)),actions:[IconButton(onPressed:restart,icon:const Icon(Icons.refresh_rounded))]),body:child);}
class _Start extends StatelessWidget{final String title,desc,info;final VoidCallback play;const _Start(this.title,this.desc,this.info,this.play);@override Widget build(BuildContext c)=>Center(child:Container(margin:const EdgeInsets.all(22),padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:const Color(0xFF111522),borderRadius:BorderRadius.circular(26)),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.sports_esports_rounded,size:52),const SizedBox(height:12),Text(title,style:const TextStyle(fontSize:27,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(desc,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white70)),const SizedBox(height:10),Text(info,style:const TextStyle(color:_purple,fontWeight:FontWeight.w800)),const SizedBox(height:18),FilledButton.icon(onPressed:play,icon:const Icon(Icons.play_arrow),label:const Text('START GAME'))])));}
class _End extends StatelessWidget{final String title;final int score;final VoidCallback again;const _End(this.title,this.score,this.again);@override Widget build(BuildContext c)=>Center(child:Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:const Color(0xFF111522),borderRadius:BorderRadius.circular(24)),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.emoji_events_rounded,size:44),Text(title,style:const TextStyle(fontSize:25,fontWeight:FontWeight.w900)),Text('Score '+score.toString()),const SizedBox(height:12),FilledButton(onPressed:again,child:const Text('Main Lagi'))])));}

class _Snake extends StatefulWidget{const _Snake();@override State<_Snake> createState()=>_SnakeState();}
class _SnakeState extends State<_Snake>{Timer?tm;final r=Random();List<Point<int>>s=[];Point<int>food=const Point(5,5),d=const Point(1,0);int score=0;bool run=false,over=false;void reset(){s=[const Point(8,8),const Point(7,8),const Point(6,8)];do{food=Point(r.nextInt(16),r.nextInt(16));}while(s.contains(food));}void start(){setState((){run=true;over=false;score=0;d=const Point(1,0);reset();});tm=Timer.periodic(const Duration(milliseconds:110),(_)=>tick());}void tick(){if(!mounted||!run||over)return;setState((){final h=s.first,n=Point(h.x+d.x,h.y+d.y);if(n.x<0||n.x>=16||n.y<0||n.y>=16||s.contains(n)){over=true;tm?.cancel();return;}s=[n,...s];if(n==food){score++;do{food=Point(r.nextInt(16),r.nextInt(16));}while(s.contains(food));}else{s.removeLast();}});}void turn(Point<int>x){if(x.x+d.x==0&&x.y+d.y==0)return;d=x;}void restart(){tm?.cancel();if(mounted)setState((){run=false;over=false;score=0;reset();});}@override void dispose(){tm?.cancel();super.dispose();}@override Widget build(BuildContext c)=>_Shell('Snake',Stack(children:[if(!run)Positioned.fill(child:_Start('Snake','Makan food dan jangan tabrak diri sendiri.','16 × 16 • SPEED UP',start)),if(run)Column(children:[Text('SCORE '+score.toString()),Expanded(child:Center(child:AspectRatio(aspectRatio:1,child:CustomPaint(painter:_SnakePaint(s,food))))),Row(mainAxisAlignment:MainAxisAlignment.center,children:[IconButton.filledTonal(onPressed:()=>turn(const Point(-1,0)),icon:const Icon(Icons.arrow_back)),IconButton.filledTonal(onPressed:()=>turn(const Point(0,-1)),icon:const Icon(Icons.arrow_upward)),IconButton.filledTonal(onPressed:()=>turn(const Point(0,1)),icon:const Icon(Icons.arrow_downward)),IconButton.filledTonal(onPressed:()=>turn(const Point(1,0)),icon:const Icon(Icons.arrow_forward))])]),if(over)Positioned.fill(child:_End('GAME OVER',score,restart))]),restart);}
class _SnakePaint extends CustomPainter{final List<Point<int>>s;final Point<int>f;_SnakePaint(this.s,this.f);@override void paint(Canvas c,Size z){final q=min(z.width,z.height)/16;c.drawRect(Offset.zero&z,Paint()..color=const Color(0xFF0B1220));c.drawCircle(Offset(f.x*q+q/2,f.y*q+q/2),q*.28,Paint()..color=Colors.redAccent);for(int i=s.length-1;i>=0;i--){final p=s[i];c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(p.x*q+2,p.y*q+2,q-4,q-4),const Radius.circular(6)),Paint()..color=i==0?Colors.cyanAccent:_purple);}}@override bool shouldRepaint(covariant _SnakePaint o)=>true;}

class _Twenty48 extends StatefulWidget{const _Twenty48();@override State<_Twenty48> createState()=>_Twenty48State();}
class _Twenty48State extends State<_Twenty48>{final r=Random();List<int>b=List.filled(16,0);int score=0;bool run=false,over=false;void add(){final e=[for(int i=0;i<16;i++)if(b[i]==0)i];if(e.isNotEmpty)b[e[r.nextInt(e.length)]]=r.nextBool()?2:4;}void start(){setState((){run=true;over=false;score=0;b=List.filled(16,0);add();add();});}List<int>merge(List<int>a){final v=a.where((x)=>x>0).toList();for(int i=0;i<v.length-1;i++)if(v[i]==v[i+1]){v[i]*=2;score+=v[i];v.removeAt(i+1);}while(v.length<4)v.add(0);return v;}bool can(){if(b.contains(0))return true;for(int i=0;i<16;i++){if(i%4<3&&b[i]==b[i+1])return true;if(i<12&&b[i]==b[i+4])return true;}return false;}void mv(int dy,int dx){if(!run||over)return;final old=b.toString();if(dy==0)for(int y=0;y<4;y++){final a=[for(int x=0;x<4;x++)b[y*4+x]],q=merge(dx<0?a:a.reversed.toList()),z=dx<0?q:q.reversed.toList();for(int x=0;x<4;x++)b[y*4+x]=z[x];}else for(int x=0;x<4;x++){final a=[for(int y=0;y<4;y++)b[y*4+x]],q=merge(dy<0?a:a.reversed.toList()),z=dy<0?q:q.reversed.toList();for(int y=0;y<4;y++)b[y*4+x]=z[y];}if(old!=b.toString()){add();setState(()=>over=!can());}}void restart(){if(mounted)setState((){run=false;over=false;b=List.filled(16,0);score=0;});}@override Widget build(BuildContext c)=>_Shell('2048',GestureDetector(onHorizontalDragEnd:(d){final v=d.primaryVelocity??0;if(v.abs()>30)mv(0,v>0?1:-1);},onVerticalDragEnd:(d){final v=d.primaryVelocity??0;if(v.abs()>30)mv(v>0?1:-1,0);},child:Stack(children:[if(!run)Positioned.fill(child:_Start('2048','Geser ubin dan gabungkan angka.','ENDLESS • PUZZLE',start)),if(run)Padding(padding:const EdgeInsets.all(16),child:Column(children:[Text('SCORE '+score.toString()),Expanded(child:Center(child:AspectRatio(aspectRatio:1,child:GridView.builder(itemCount:16,physics:const NeverScrollableScrollPhysics(),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:4,crossAxisSpacing:8,mainAxisSpacing:8),itemBuilder:(_,i)=>Container(decoration:BoxDecoration(color:b[i]==0?const Color(0xFF1A1E2A):_purple,borderRadius:BorderRadius.circular(12)),child:Center(child:Text(b[i]==0?'':b[i].toString(),style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900))))))]))),if(over)Positioned.fill(child:_End('GAME OVER',score,restart))])),restart);}

class _Tetris extends StatefulWidget{const _Tetris();@override State<_Tetris> createState()=>_TetrisState();}
class _TetrisState extends State<_Tetris>{Timer?tm;final r=Random();List<List<int>>g=List.generate(20,(_)=>List.filled(10,0));List<Point<int>>p=[];int x=3,y=0,score=0;bool run=false,over=false;final shapes=<List<Point<int>>>[[const Point(0,0),const Point(1,0),const Point(2,0),const Point(3,0)],[const Point(0,0),const Point(1,0),const Point(0,1),const Point(1,1)],[const Point(1,0),const Point(0,1),const Point(1,1),const Point(2,1)]];bool ok(List<Point<int>>q,int xx,int yy)=>q.every((a){final X=xx+a.x,Y=yy+a.y;return X>=0&&X<10&&Y>=0&&Y<20&&g[Y][X]==0;});void spawn(){p=List.from(shapes[r.nextInt(shapes.length)]);x=3;y=0;if(!ok(p,x,y)){over=true;tm?.cancel();}}void start(){setState((){run=true;over=false;score=0;g=List.generate(20,(_)=>List.filled(10,0));spawn();});tm=Timer.periodic(const Duration(milliseconds:500),(_)=>down());}void down(){if(!run||over)return;if(ok(p,x,y+1))setState(()=>y++);else lock();}void lock(){setState((){for(final a in p)g[y+a.y][x+a.x]=1;for(int yy=19;yy>=0;yy--)if(g[yy].every((v)=>v>0)){g.removeAt(yy);g.insert(0,List.filled(10,0));score+=100;}spawn();});}void move(int d){if(run&&!over&&ok(p,x+d,y))setState(()=>x+=d);}void restart(){tm?.cancel();if(mounted)setState((){run=false;over=false;score=0;g=List.generate(20,(_)=>List.filled(10,0));});}@override void dispose(){tm?.cancel();super.dispose();}@override Widget build(BuildContext c)=>_Shell('Tetris',Column(children:[if(!run)Expanded(child:_Start('Tetris','Susun blok dan bersihkan baris.','10 × 20 • ENDLESS',start)),if(run)Text('SCORE '+score.toString()),if(run)Expanded(child:Center(child:AspectRatio(aspectRatio:.5,child:CustomPaint(painter:_TetPaint(g,p,x,y))))),if(run)Row(mainAxisAlignment:MainAxisAlignment.center,children:[IconButton.filledTonal(onPressed:()=>move(-1),icon:const Icon(Icons.arrow_back)),IconButton.filledTonal(onPressed:down,icon:const Icon(Icons.arrow_downward)),IconButton.filledTonal(onPressed:()=>move(1),icon:const Icon(Icons.arrow_forward))]),if(over)Expanded(child:_End('GAME OVER',score,restart))]),restart);}
class _TetPaint extends CustomPainter{final List<List<int>>g;final List<Point<int>>p;final int x,y;_TetPaint(this.g,this.p,this.x,this.y);@override void paint(Canvas c,Size s){final q=min(s.width/10,s.height/20);c.drawRect(Offset.zero&s,Paint()..color=const Color(0xFF090D17));for(int yy=0;yy<20;yy++)for(int xx=0;xx<10;xx++)if(g[yy][xx]>0)c.drawRect(Rect.fromLTWH(xx*q,yy*q,q-1,q-1),Paint()..color=_purple);for(final a in p)c.drawRect(Rect.fromLTWH((x+a.x)*q,(y+a.y)*q,q-1,q-1),Paint()..color=Colors.cyanAccent);}@override bool shouldRepaint(covariant _TetPaint o)=>true;}

class _Flappy extends StatefulWidget{const _Flappy();@override State<_Flappy> createState()=>_FlappyState();}
class _FlappyState extends State<_Flappy>{Timer?tm;final r=Random();double y=.5,vy=0,px=1.1,g=.5;int score=0;bool run=false,over=false;void start(){tm?.cancel();setState((){run=true;over=false;y=.5;vy=0;px=1.1;g=.5;score=0;});tm=Timer.periodic(const Duration(milliseconds:16),(_)=>tick());}void tick(){if(!mounted||!run||over)return;setState((){vy+=.00052;y+=vy;px-=.006;if(px<-.18){px=1.1;g=.27+r.nextDouble()*.42;score++;}if(y<.02||y>.98||(px<.61&&px>.31&&(y<g-.15||y>g+.15))){over=true;tm?.cancel();}});}void flap(){if(run&&!over)setState(()=>vy=-.0105);}void restart(){tm?.cancel();if(mounted)setState((){run=false;over=false;score=0;y=.5;vy=0;px=1.1;});}@override void dispose(){tm?.cancel();super.dispose();}@override Widget build(BuildContext c)=>_Shell('Flappy',GestureDetector(onTap:flap,behavior:HitTestBehavior.opaque,child:Stack(children:[Positioned.fill(child:CustomPaint(painter:_FlapPaint(y,px,g))),if(!run)Positioned.fill(child:Container(color=Colors.black45,child:_Start('Flappy','Tap untuk terbang melewati pipa.','ONE TAP • ENDLESS',start))),if(run)Positioned(top:12,left:12,child:_Tag('SCORE '+score.toString())),if(over)Positioned.fill(child:_End('GAME OVER',score,restart))])),restart);}
class _FlapPaint extends CustomPainter{final double y,x,g;_FlapPaint(this.y,this.x,this.g);@override void paint(Canvas c,Size s){c.drawRect(Offset.zero&s,Paint()..color=const Color(0xFF071522));final p=Paint()..color=Colors.green;c.drawRect(Rect.fromLTWH(x*s.width,0,s.width*.13,max(0,s.height*(g-.15))),p);c.drawRect(Rect.fromLTWH(x*s.width,s.height*(g+.15),s.width*.13,max(0,s.height*(.99-g-.15))),p);c.drawCircle(Offset(s.width*.5,y*s.height),18,Paint()..color=Colors.amber);}@override bool shouldRepaint(covariant _FlapPaint o)=>true;}

class _Breakout extends StatefulWidget{const _Breakout();@override State<_Breakout> createState()=>_BreakoutState();}
class _BreakoutState extends State<_Breakout>{Timer?tm;double x=.5,y=.75,vx=.008,vy=-.01,pad=.5;List<bool>b=List.filled(30,true);int score=0,lives=3;bool run=false,over=false;void start(){setState((){run=true;over=false;score=0;lives=3;x=.5;y=.75;vx=.008;vy=-.01;pad=.5;b=List.filled(30,true);});tm=Timer.periodic(const Duration(milliseconds:16),(_)=>tick());}void tick(){if(!mounted||!run||over)return;setState((){x+=vx;y+=vy;if(x<.03||x>.97){vx=-vx;}if(y<.04)vy=vy.abs();if(y>.88&&y<.94&&(x-pad).abs()<.16)vy=-vy.abs();final cc=((x-.08)/.18).floor(),rr=((y-.06)/.055).floor();if(cc>=0&&cc<5&&rr>=0&&rr<6){final i=rr*5+cc;if(b[i]){b[i]=false;score+=10;vy=-vy;}}if(y>1.03){lives--;if(lives<=0){over=true;tm?.cancel();}else{x=.5;y=.75;vy=-.01;}}if(b.every((v)=>!v)){over=true;tm?.cancel();}});}void restart(){tm?.cancel();if(mounted)setState((){run=false;over=false;score=0;lives=3;b=List.filled(30,true);});}@override void dispose(){tm?.cancel();super.dispose();}@override Widget build(BuildContext c)=>_Shell('Breakout',Column(children:[if(!run)Expanded(child:_Start('Breakout','Gerakkan paddle dan hancurkan brick.','30 BRICKS • 3 LIVES',start)),if(run)Text('SCORE '+score.toString()+' • LIVES '+lives.toString()),if(run)Expanded(child:GestureDetector(onHorizontalDragUpdate:(d)=>setState(()=>pad=(pad+d.delta.dx/MediaQuery.sizeOf(c).width).clamp(.12,.88)),child:CustomPaint(painter:_BreakPaint(x,y,pad,b)))),if(over)Expanded(child:_End(b.every((v)=>!v)?'YOU WIN':'GAME OVER',score,restart))]),restart);}
class _BreakPaint extends CustomPainter{final double x,y,p;final List<bool>b;_BreakPaint(this.x,this.y,this.p,this.b);@override void paint(Canvas c,Size s){c.drawRect(Offset.zero&s,Paint()..color=const Color(0xFF090D17));for(int i=0;i<30;i++)if(b[i]){final col=i%5,row=i~/5;c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(s.width*(.08+col*.18),s.height*(.06+row*.055),s.width*.15,s.height*.04),const Radius.circular(5)),Paint()..color=_purple);}c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(s.width*(p-.12),s.height*.92,s.width*.24,12),const Radius.circular(8)),Paint()..color=Colors.white);c.drawCircle(Offset(x*s.width,y*s.height),8,Paint()..color=Colors.cyanAccent);}@override bool shouldRepaint(covariant _BreakPaint o)=>true;}

class _Memory extends StatefulWidget{const _Memory();@override State<_Memory> createState()=>_MemoryState();}
class _MemoryState extends State<_Memory>{final r=Random();List<int>cards=[];List<int>open=[];Set<int>match={};bool run=false,lock=false,over=false;int moves=0;void start(){cards=[0,0,1,1,2,2,3,3,4,4,5,5]..shuffle(r);setState((){run=true;open=[];match={};lock=false;over=false;moves=0;});}void tap(int i){if(!run||lock||open.contains(i)||match.contains(i))return;setState(()=>open=[...open,i]);if(open.length==2){lock=true;moves++;final a=open[0],b=open[1];if(cards[a]==cards[b])Future.delayed(const Duration(milliseconds:300),(){if(mounted)setState((){match.addAll([a,b]);open=[];lock=false;over=match.length==cards.length;});});else Future.delayed(const Duration(milliseconds:600),(){if(mounted)setState((){open=[];lock=false;});});}}void restart(){if(mounted)setState((){run=false;open=[];match={};lock=false;over=false;moves=0;});}@override Widget build(BuildContext c)=>_Shell('Memory',Stack(children:[if(!run)Positioned.fill(child:_Start('Memory','Cari semua pasangan kartu yang sama.','12 CARDS • 6 PAIRS',start)),if(run)Padding(padding:const EdgeInsets.all(16),child:Column(children:[Text('MOVES '+moves.toString()),Expanded(child:GridView.builder(itemCount:12,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:9,mainAxisSpacing:9),itemBuilder:(_,i){final v=open.contains(i)||match.contains(i);return InkWell(onTap:()=>tap(i),child:Container(decoration:BoxDecoration(color:v?_purple:const Color(0xFF171D2C),borderRadius:BorderRadius.circular(16)),child:Center(child:v?Text((cards[i]+1).toString(),style:const TextStyle(fontSize:27,fontWeight:FontWeight.w900)):const Icon(Icons.help_outline,color:Colors.white38,size:28))));}))])),if(over)Positioned.fill(child:_End('ALL PAIRS FOUND',moves,restart))]),restart);}

class _Pong extends StatefulWidget{const _Pong();@override State<_Pong> createState()=>_PongState();}
class _PongState extends State<_Pong>{Timer?tm;final r=Random();double bx=.5,by=.5,vx=.008,vy=.006,me=.5,ai=.5;int you=0,bot=0;bool run=false,over=false;void start(){setState((){run=true;over=false;you=0;bot=0;bx=.5;by=.5;vx=.008;vy=.006;});tm=Timer.periodic(const Duration(milliseconds:16),(_)=>tick());}void reset(){bx=.5;by=.5;vx=vx>0?.008:-.008;vy=r.nextBool()?.006:-.006;}void tick(){if(!mounted||!run||over)return;setState((){bx+=vx;by+=vy;if(by<.04||by>.96)vy=-vy;ai+=(by-ai)*.055;if(bx<.09){if((by-me).abs()<.15)vx=vx.abs();else{bot++;reset();}}if(bx>.91){if((by-ai).abs()<.15)vx=-vx.abs();else{you++;reset();}}if(you>=7||bot>=7){over=true;tm?.cancel();}});}void restart(){tm?.cancel();if(mounted)setState((){run=false;over=false;you=0;bot=0;});}@override void dispose(){tm?.cancel();super.dispose();}@override Widget build(BuildContext c)=>_Shell('Pong',Column(children:[if(!run)Expanded(child:_Start('Pong','Geser paddle kiri untuk mengalahkan AI.','FIRST TO 7 • VS AI',start)),if(run)Text('YOU '+you.toString()+' • AI '+bot.toString()),if(run)Expanded(child:LayoutBuilder(builder:(c,z)=>GestureDetector(onVerticalDragUpdate:(d)=>setState(()=>me=(d.localPosition.dy/z.maxHeight).clamp(.08,.92)),onTapDown:(d)=>setState(()=>me=(d.localPosition.dy/z.maxHeight).clamp(.08,.92)),child:CustomPaint(painter:_PongPaint(bx,by,me,ai))))),if(over)Expanded(child:_End(you>bot?'YOU WIN':'AI WINS',you,restart))]),restart);}
class _PongPaint extends CustomPainter{final double x,y,m,a;_PongPaint(this.x,this.y,this.m,this.a);@override void paint(Canvas c,Size s){c.drawRect(Offset.zero&s,Paint()..color=const Color(0xFF08111F));c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(10,m*s.height-42,10,84),const Radius.circular(6)),Paint()..color=Colors.cyanAccent);c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(s.width-20,a*s.height-42,10,84),const Radius.circular(6)),Paint()..color=_purple);c.drawCircle(Offset(x*s.width,y*s.height),9,Paint()..color=Colors.white);}@override bool shouldRepaint(covariant _PongPaint o)=>true;}

class _Whack extends StatefulWidget{const _Whack();@override State<_Whack> createState()=>_WhackState();}
class _WhackState extends State<_Whack>{Timer?tm;final r=Random();int active=-1,score=0,time=30;bool run=false,over=false;void start(){setState((){run=true;over=false;score=0;time=30;active=r.nextInt(9);});tm=Timer.periodic(const Duration(seconds:1),(_){if(!mounted)return;setState((){time--;active=r.nextInt(9);if(time<=0){over=true;active=-1;tm?.cancel();}});});}void hit(int i){if(run&&!over&&i==active){score++;active=r.nextInt(9);}}void restart(){tm?.cancel();if(mounted)setState((){run=false;over=false;score=0;time=30;active=-1;});}@override void dispose(){tm?.cancel();super.dispose();}@override Widget build(BuildContext c)=>_Shell('Whack-a-Mole',Stack(children:[if(!run)Positioned.fill(child:_Start('Whack-a-Mole','Tap target secepat mungkin.','30 SECONDS • FAST TAP',start)),if(run)Padding(padding:const EdgeInsets.all(16),child:Column(children:[Text('TIME '+time.toString()+' • SCORE '+score.toString()),Expanded(child:GridView.builder(itemCount:9,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:12,mainAxisSpacing:12),itemBuilder:(_,i)=>InkWell(onTap:()=>hit(i),child:Container(decoration:BoxDecoration(color:const Color(0xFF151B2A),borderRadius:BorderRadius.circular(22)),child:Center(child:Icon(i==active?Icons.bolt_rounded:Icons.circle_outlined,size:i==active?58:35,color:i==active?Colors.amber:Colors.white12))))))])),if(over)Positioned.fill(child:_End('TIME UP',score,restart))]),restart);}

class _Mines extends StatefulWidget{const _Mines();@override State<_Mines> createState()=>_MinesState();}
class _MinesState extends State<_Mines>{final r=Random();List<bool>mine=List.filled(64,false),open=List.filled(64,false),flag=List.filled(64,false);bool run=false,over=false,win=false;int safe=0;void start(){mine=List.filled(64,false);open=List.filled(64,false);flag=List.filled(64,false);safe=0;final ids=List.generate(64,(i)=>i)..shuffle(r);for(final i in ids.take(10))mine[i]=true;setState((){run=true;over=false;win=false;});}int count(int i){final rr=i~/8,cc=i%8;var n=0;for(int dr=-1;dr<=1;dr++)for(int dc=-1;dc<=1;dc++){final y=rr+dr,x=cc+dc;if(y>=0&&y<8&&x>=0&&x<8&&mine[y*8+x])n++;}return n;}void reveal(int i){if(!run||over||open[i]||flag[i])return;if(mine[i]){setState((){over=true;open[i]=true;});return;}open[i]=true;safe++;setState((){win=safe>=54;over=win;});}void restart(){if(mounted)setState((){run=false;over=false;win=false;safe=0;});}@override Widget build(BuildContext c)=>_Shell('Minesweeper',Stack(children:[if(!run)Positioned.fill(child:_Start('Minesweeper','Tap untuk buka. Tahan untuk flag.','8 × 8 • 10 MINES',start)),if(run)Padding(padding:const EdgeInsets.all(14),child:Column(children:[Text('SAFE '+safe.toString()),Expanded(child:GridView.builder(itemCount:64,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:8,crossAxisSpacing:4,mainAxisSpacing:4),itemBuilder:(_,i)=>GestureDetector(onTap:()=>reveal(i),onLongPress:()=>setState(()=>flag[i]=!flag[i]),child:Container(decoration:BoxDecoration(color:open[i]?const Color(0xFF20283A):const Color(0xFF111827),borderRadius:BorderRadius.circular(5)),child:Center(child:Text(open[i]?(mine[i]?'X':(count(i)==0?'':count(i).toString())):(flag[i]?'⚑':'•')))))))])),if(over)Positioned.fill(child:_End(win?'BOARD CLEARED':'BOOM',safe,restart))]),restart);}

class _Simon extends StatefulWidget{const _Simon();@override State<_Simon> createState()=>_SimonState();}
class _SimonState extends State<_Simon>{final r=Random();final colors=const[Colors.red,Colors.green,Colors.blue,Colors.amber];final seq=<int>[];Timer?tm;int step=0,flash=-1,round=0;bool run=false,accept=false,over=false;void start(){tm?.cancel();seq.clear();setState((){run=true;over=false;accept=false;round=0;step=0;flash=-1;});next();}void next(){seq.add(r.nextInt(4));round=seq.length;step=0;accept=false;play(0);}void play(int i){if(!mounted)return;if(i>=seq.length){setState(()=>accept=true);return;}setState(()=>flash=seq[i]);tm=Timer(const Duration(milliseconds:320),(){if(!mounted)return;setState(()=>flash=-1);tm=Timer(const Duration(milliseconds:160),()=>play(i+1));});}void tap(int i){if(!run||over||!accept)return;if(seq[step]!=i){setState((){over=true;accept=false;});return;}setState(()=>step++);if(step>=seq.length){setState(()=>accept=false);tm=Timer(const Duration(milliseconds:450),(){if(mounted&&!over)next();});}}void restart(){tm?.cancel();if(mounted)setState((){run=false;over=false;accept=false;seq.clear();round=0;step=0;flash=-1;});}@override void dispose(){tm?.cancel();super.dispose();}@override Widget build(BuildContext c)=>_Shell('Simon Says',Stack(children:[if(!run)Positioned.fill(child:_Start('Simon Says','Ingat urutan warna lalu ulangi.','ENDLESS • MEMORY',start)),if(run)Padding(padding:const EdgeInsets.all(18),child:Column(children:[Text('ROUND '+round.toString()+' • '+(accept?'YOUR TURN':'WATCH')),Expanded(child:GridView.count(crossAxisCount:2,crossAxisSpacing:14,mainAxisSpacing:14,children:[for(int i=0;i<4;i++)GestureDetector(onTap:()=>tap(i),child:AnimatedContainer(duration:const Duration(milliseconds:110),decoration:BoxDecoration(color:flash==i?colors[i]:colors[i].withOpacity(.25),borderRadius:BorderRadius.circular(28)),child:const Icon(Icons.circle,size:38,color:Colors.white54))))]))])),if(over)Positioned.fill(child:_End('WRONG MOVE',max(0,round-1),restart))]),restart);}
