name: Nexora Web Test - Live

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.2"
          channel: stable
          cache: true

      - name: Add web platform
        run: flutter create . --platforms web

      - name: Get packages
        run: flutter pub get

      - name: Remove generated sample test
        run: rm -f test/widget_test.dart

      - name: Analyze
        run: flutter analyze

      - name: Build web
        run: flutter build web --release --base-href /Nexora/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
