name: Nexora Web Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  web-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.2"
          channel: stable
          cache: true

      - name: Add web platform
        run: flutter create . --platforms web

      - name: Get packages
        run: flutter pub get

      - name: Remove generated sample test
        run: rm -f test/widget_test.dart

      - name: Analyze
        run: flutter analyze

      - name: Build web release
        run: flutter build web --release

      - name: Upload Web Test
        uses: actions/upload-artifact@v4
        with:
          name: Nexora-Web-Test
          path: build/web
          if-no-files-found: error
